# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gitHubUserList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gitHubUserList

  target 'gitHubUserListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gitHubUserListUITests' do
    # Pods for testing
  end

pod 'SwiftyJSON'
pod 'Alamofire'

end
